# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPoU-PDdbpT6acei1x2Ksui6Giyh-XhQ
"""

import pandas as pd
df = pd.DataFrame ({
               'Ism Familiya' :    ['muhamedova shohida ORIBJON qizi',' aliyeva osiyo SAIDJON qizi',' xusanova robiya ABDUJALIL qizi',' sharipova aziza G‘ANIJON qizi',' soliyeva shabona SHERZOD qizi',' MAMATVALIYEV DILSHODBEK XALIMJON O‘G‘LI',' MIRZAHAMIDOV JALOLIDDIN MUZAFFAR O‘G‘LI',' NE’MATOVA DILDORAXON XAYRULLOJON QIZI',' NURMUHAMMADOV MUHAMMAD MUXIDDIN O‘G‘LI',' QAMBARALIYEVA NIGORAXON MUXAMMADJON QIZI','QAMBAROV SAMANDARBEK XAYDARALI O‘G‘LI',' RAXMONOV BEKZODJON MUXAMMADMUROT O‘G‘LI',' SHAMSIDINOV SHERZODJON HOJIBOY ZODA','SOBIROV MUHAMMADJON IBROHIM O‘G‘L','SODIQOVA MAXLIYOXON SAFARALI QIZI','SULAYMONOVA MAXLIYOXON VALIJON QIZI','TURG‘UNBOYEV DIYORBEK OYBEK O‘G‘LI','  YO‘LDASHEV XUSNIDDIN XASANBOY O‘G‘LI',' yunusaliyeva saboxat otabek qizi' ] ,

               'yoshi':   ['20', '23', '10', '43', '12', '24', '13', '14', '26', '25', '38', '35', '33', '31', '28', '29', '30', '21', '30'],
               'kursi':   ['3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3'] ,
                  'tugulgan yili':['2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005','2005',]
                 })
print(df)

df.to_excel('guruh.xlsx', index=False, sheet_name='sheet1')